### ISSUE TITLE
Containerize application

### ISSUE THREAD

**Issue by hvalfangst** [hvalfangst/Axum-API-with-Auth#3]
Create a Dockerfile as well as a docker-compose which contains our Axum API and PostgreSQL container, sharing the same internal docker network.

**Comment by TemaDeveloper** [comment]
If you still need the docker-compose.yml file here it is 
There is a Postrgres image

version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "10100:5432"
